### PR TITLE
Fix request for AudioFeatures being too large

### LINKED ISSUE #212: 502 response from API when attempting to load audio features on saved tracks with many tracks in them
**Describe the bug**
As noted by @jejacks0n (thanks!), trying to download saved tracks with too many musics gets a 502 response from the Spotify API, so no files can be downloaded.

**To Reproduce**
Don´t know the exact number but saved tracks with too many songs (> 700 in my case) receives a 502 response.
Tried to reproduce using playlists with > 1000 tracks but it worked flawlessly, apparently it only affects saved tracks.

**Expected behavior**
Being able to download large collection of saved tracks.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 116

### PR DESCRIPTION
**Pull request by pedrorault**
# Title
Solves the 502 response when downloading large collection of saved tracks.

## Details
Extracting audio features using chunks of size MAX_LIMIT_DEFAULT (50) instead of searching the whole list in one request.

## Testing
Being able to download my saved tracks

## Checklist
[X] Ran eslint/prettier formatting
[X] Tests are passing (no tests yet)
[X] Feature is considered complete

## Issues this resolves
fixes #212

### CODE REVIEW

**Comment by pedrorault** [comment]
@phyzical I don´t know if it is the preferred solution since large playlists are not affected by this error, any comments are welcome

File: lib/api.js [hunk 1]
```diff
@@ -501,9 +501,13 @@ export async function extractSavedTracks() {
...
-  );
+  let audioFeatures = [];
+  for(let chunk of trackIds.chunk(MAX_LIMIT_DEFAULT)) {
+    audioFeatures.push(await callSpotifyApi(
+      async () => (await spotifyApi.getAudioFeaturesForTracks(
+        chunk,
+      )).body.audio_features,
+    ));
+  }
+  return audioFeatures;
```
Comment (phyzical) [inline lib/api.js:512]:
```suggestion
  let audioFeatures = [];
  for(let chunk of trackIds.chunk(MAX_LIMIT_DEFAULT)) {
    audioFeatures.push(...(await callSpotifyApi(
      async () => (await spotifyApi.getAudioFeaturesForTracks(
        chunk,
      )).body.audio_features,
    )));
  }
  return audioFeatures;
```

Comment (phyzical) [reply lib/api.js:512]: @pedrorault this is untested but i think we also need to unwrap the array, or concat instead of push

**Comment by phyzical** [comment]
tested with these changes locally, still got bpm ect
